### ISSUE TITLE
Segmentation fault when benchmarking Container::CRBTreeMap

### ISSUE THREAD

**Issue by copiousfreetime** [kanwei/algorithms#24]
I was attempting to benchmark `Conaitiner::RBTreeMap` against `::RBTree` and am able to consistently get a segmentation fault that appears to be triggered by `Container::RBTreeMap` when used within the context of `Benchmark`.

I the simplest use case that consistently segfaults for me here https://gist.github.com/copiousfreetime/46ce78f08885b24bc8dd.

It always segfaults during a write operation.

**Comment by kanwei** [comment]
Can't reproduce.
